---
#- name: Print all available facts
#  ansible.builtin.debug:
#    var: ansible_facts
- import_tasks: precheck.yml
- name: Check files directory exists
  file:
    name: files/
    state: directory
    mode: 0755
  run_once: true
  delegate_to: localhost
- include_tasks: "download_{{ ansible_facts.pkg_mgr }}.yml"
- include_tasks: "install_{{ ansible_facts.pkg_mgr }}.yml"
- import_tasks: configure.yml
